export const styles = {
    sectionLabel: {
        wrapper: "flex items-center gap-4 mb-10",
        index: "font-mono text-xs text-primary tracking-widest",
        title: "font-mono text-xs uppercase tracking-[0.25em] text-muted-foreground",
        line: "h-px flex-1 bg-border",
    },
    hero: {
        section: "relative px-6 pt-20 pb-16 md:pt-28 md:pb-24 border-b border-border",
        container: "max-w-6xl mx-auto",
        badgeWrap: "flex items-center gap-3 mb-8 font-mono text-xs text-muted-foreground reveal-up",
        badgeDot: "flex h-2 w-2 bg-primary animate-pulse",
        badgeText: "tracking-widest uppercase",
        title: "font-sans font-bold tracking-tighter text-[clamp(2.75rem,11vw,8.5rem)] leading-[0.88] text-balance reveal-up",
        titleSub: "text-muted-foreground",
        titleDot: "text-primary",
        row: "mt-10 grid md:grid-cols-12 gap-8 items-end",
        description: "md:col-span-7 text-lg md:text-xl text-muted-foreground leading-relaxed max-w-2xl",
        descriptionHighlight: "text-foreground",
        infoWrap: "md:col-span-5 md:justify-self-end w-full md:w-auto",
        infoList: "flex flex-col gap-3 font-mono text-xs",
        infoItem: "flex items-center gap-3 text-muted-foreground",
        infoIcon: "w-4 h-4 text-primary",
        buttonsWrap: "flex flex-wrap gap-3 mt-6",
        downloadButton: "rounded-none bg-foreground text-background hover:bg-primary hover:text-primary-foreground font-mono text-xs uppercase tracking-widest cursor-pointer",
        downloadIcon: "w-4 h-4 mr-2",
        portfolioButton: "rounded-none border-border bg-transparent text-foreground hover:bg-secondary font-mono text-xs uppercase tracking-widest cursor-pointer",
        scrollWrap: "mt-16 flex items-center gap-3 font-mono text-xs text-muted-foreground",
        scrollIcon: "w-4 h-4 animate-bounce",
        scrollText: "tracking-widest uppercase",
    },
    marquee: {
        section: "border-b border-border overflow-hidden bg-secondary/30",
        track: "flex whitespace-nowrap py-4",
        group: "flex animate-marquee shrink-0",
        item: "flex items-center font-mono text-sm text-muted-foreground",
        itemText: "px-6 uppercase tracking-widest",
        itemSlash: "text-primary",
    },
    stats: {
        section: "px-6 py-16 border-b border-border",
        grid: "max-w-6xl mx-auto grid grid-cols-2 md:grid-cols-4",
        card: "group p-6 border-r border-border last:border-r-0 [&:nth-child(2)]:border-r-0 md:[&:nth-child(2)]:border-r [&:nth-child(-n+2)]:border-b [&:nth-child(-n+2)]:md:border-b-0 border-border",
        cardHeader: "flex items-center justify-between mb-4",
        cardIcon: "w-5 h-5 text-primary",
        cardIndex: "font-mono text-[10px] text-muted-foreground",
        cardValue: "font-sans text-5xl font-bold tracking-tighter mb-3 group-hover:text-primary transition-colors",
        cardLabel: "font-mono text-xs text-muted-foreground leading-snug",
    },
    about: {
        section: "px-6 py-20 border-b border-border",
        container: "max-w-6xl mx-auto",
        grid: "grid lg:grid-cols-12 gap-12",
        textCol: "lg:col-span-7",
        lead: "font-sans text-2xl md:text-3xl font-medium tracking-tight leading-snug text-balance mb-8",
        paragraphs: "space-y-4 text-muted-foreground leading-relaxed",
        skillsCol: "lg:col-span-5",
        skillsList: "border-t border-border",
        skillItem: "group flex items-center gap-4 py-4 border-b border-border",
        skillIndex: "font-mono text-[10px] text-primary w-6",
        skillName: "font-mono text-sm font-medium uppercase tracking-wider w-40 shrink-0 group-hover:text-primary transition-colors",
        skillLevel: "font-mono text-xs text-muted-foreground leading-snug",
    },
    experience: {
        section: "px-6 py-20 border-b border-border",
        container: "max-w-6xl mx-auto",
        list: "border-t border-border",
        item: "group w-full text-left grid md:grid-cols-12 gap-4 md:gap-8 py-8 border-b border-border hover:bg-secondary/40 transition-colors px-2 -mx-2 cursor-pointer",
        colLeft: "md:col-span-3 flex items-start justify-between md:block",
        company: "font-sans text-2xl font-bold tracking-tight group-hover:text-primary transition-colors",
        period: "font-mono text-[10px] uppercase tracking-widest text-muted-foreground mt-1",
        colMid: "md:col-span-6",
        role: "font-mono text-sm text-foreground mb-1",
        meta: "font-mono text-[10px] uppercase tracking-widest text-primary mb-3",
        description: "text-sm text-muted-foreground leading-relaxed",
        tagsWrap: "flex flex-wrap gap-2 mt-4",
        tag: "font-mono text-[10px] uppercase tracking-wider text-muted-foreground border border-border px-2 py-1",
        colRight: "md:col-span-3 flex md:justify-end items-start",
        arrowIcon: "w-5 h-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform",
    },
    projects: {
        section: "px-6 py-20 border-b border-border",
        container: "max-w-6xl mx-auto",
        grid: "grid md:grid-cols-2 lg:grid-cols-3 border-t border-l border-border",
        card: "group relative text-left border-r border-b border-border overflow-hidden cursor-pointer min-h-[22rem] flex flex-col",
        imageWrap: "absolute inset-0 z-0",
        image: "w-full h-full object-cover opacity-20 grayscale transition-all duration-500 group-hover:opacity-30 group-hover:grayscale-0 group-hover:scale-105",
        imageGradient: "absolute inset-0 bg-gradient-to-t from-card via-card/90 to-card/40",
        content: "relative z-10 flex flex-col h-full p-6",
        header: "flex items-start justify-between mb-6",
        icon: "text-primary text-2xl",
        badgesWrap: "flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest",
        badge: "text-primary border border-primary/40 px-2 py-1",
        yearBadge: "text-muted-foreground border border-border px-2 py-1",
        title: "font-sans text-2xl font-bold tracking-tight mb-2 group-hover:text-primary transition-colors",
        description: "text-sm text-muted-foreground leading-relaxed mb-4 flex-1",
        typeWrap: "mb-4",
        typeLabel: "font-mono text-[10px] uppercase tracking-widest text-muted-foreground mb-2",
        techWrap: "flex flex-wrap gap-1.5",
        tech: "font-mono text-[10px] uppercase tracking-wider text-foreground border border-border px-2 py-0.5",
        footer: "flex items-center gap-2 font-mono text-xs text-muted-foreground group-hover:text-primary transition-colors",
        footerText: "uppercase tracking-widest",
        footerIcon: "w-4 h-4 group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform",
    },
    cta: {
        section: "px-6 py-24",
        container: "max-w-6xl mx-auto",
        wrap: "flex flex-col items-start gap-8",
        title: "font-sans font-bold tracking-tighter text-[clamp(2.25rem,8vw,6rem)] leading-[0.9] text-balance",
        titleSub: "text-muted-foreground",
        titleDot: "text-primary",
        button: "rounded-none bg-primary text-primary-foreground hover:bg-foreground hover:text-background font-mono text-sm uppercase tracking-widest h-14 px-8 cursor-pointer",
        buttonIcon: "w-4 h-4 mr-3",
    },
}
